
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CAMBIO COLOR Tiempo\n    cambio  :  expression\n            | empty\n    \n    empty :\n    \n    expression : COLOR CAMBIO COLOR\n    '
    
_lr_action_items = {'COLOR':([0,5,],[4,6,]),'$end':([0,1,2,3,6,],[-3,0,-1,-2,-4,]),'CAMBIO':([4,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cambio':([0,],[1,]),'expression':([0,],[2,]),'empty':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cambio","S'",1,None,None,None),
  ('cambio -> expression','cambio',1,'p_cambio','Semaforo.py',28),
  ('cambio -> empty','cambio',1,'p_cambio','Semaforo.py',29),
  ('empty -> <empty>','empty',0,'p_empty','Semaforo.py',35),
  ('expression -> COLOR CAMBIO COLOR','expression',3,'p_expression','Semaforo.py',41),
]
